# Generated by Django 3.2.8 on 2022-04-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acount',
            old_name='is_teacher',
            new_name='is_student',
        ),
    ]
